### PR TITLE
style: Add `.editorconfig` file

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Describes some basic formatting like indentation with spaces, indentation size, final newlines, etc.

### CODE REVIEW

**Comment by Alystrasz** [comment]
* How is this applied to source code?
* Is is applied to Typescript or Rust or both?

**Comment by GeckoEidechse** [comment]
> * How is this applied to source code?

It's technically applied to the IDE, so that when it uses certain autoformatting options, it takes the info from `.editorconfig` into account. The config file itself is supported by [a variety of IDEs either with or without extension](https://editorconfig.org/#pre-installed)-

> * Is is applied to Typescript or Rust or both?

[Both](https://github.com/GeckoEidechse/FlightCore/pull/42/files#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5bR6), though specific rules can be added for each.

**Comment by Alystrasz** [comment]
It seems to work with Visual Studio Code.
You should add a note to developers mentioning they should install an EditorConfig plugin in their IDE, otherwise LGTM :)

**Comment by GeckoEidechse** [comment]
> It seems to work with Visual Studio Code. You should add a note to developers mentioning they should install an EditorConfig plugin in their IDE, otherwise LGTM :)

Added note with 8e419dbb8bcc8c439eb8afd791c56ba7d9cdbd76

**Pull request merged**
